//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMD_FrameShot_Save.LanguageList {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMD_FrameShot_Save.LanguageList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Image compression complete:{0} 的本地化字符串。
        /// </summary>
        internal static string CompressDone {
            get {
                return ResourceManager.GetString("CompressDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressing:{0} → {1} 的本地化字符串。
        /// </summary>
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 format 的本地化字符串。
        /// </summary>
        internal static string ConvertFormatLIST {
            get {
                return ResourceManager.GetString("ConvertFormatLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Frame: {0}   的本地化字符串。
        /// </summary>
        internal static string CurrentFrameViewText {
            get {
                return ResourceManager.GetString("CurrentFrameViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitingTime 的本地化字符串。
        /// </summary>
        internal static string DelayTimeText {
            get {
                return ResourceManager.GetString("DelayTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting source files 的本地化字符串。
        /// </summary>
        internal static string DeleteSourceFilesText {
            get {
                return ResourceManager.GetString("DeleteSourceFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable image compression 的本地化字符串。
        /// </summary>
        internal static string EnableImageCompressText {
            get {
                return ResourceManager.GetString("EnableImageCompressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The software needs to be used with English input method. 的本地化字符串。
        /// </summary>
        internal static string EnglishInputMethodText {
            get {
                return ResourceManager.GetString("EnglishInputMethodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure you have selected the path, filename prefix and image format! 的本地化字符串。
        /// </summary>
        internal static string EnsurePathPrefixType {
            get {
                return ResourceManager.GetString("EnsurePathPrefixType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileSuffix 的本地化字符串。
        /// </summary>
        internal static string FilenamesuffixText {
            get {
                return ResourceManager.GetString("FilenamesuffixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        internal static string FileNameText {
            get {
                return ResourceManager.GetString("FileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string FinalSaveButtonText {
            get {
                return ResourceManager.GetString("FinalSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMD FrameShot Save 的本地化字符串。
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string FrameClearText {
            get {
                return ResourceManager.GetString("FrameClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame 的本地化字符串。
        /// </summary>
        internal static string FrameRangeText {
            get {
                return ResourceManager.GetString("FrameRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If using consecutive frames, please use the+button to obtain coordinates before entering frames 的本地化字符串。
        /// </summary>
        internal static string FrameRangeTipText {
            get {
                return ResourceManager.GetString("FrameRangeTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This button will conflict with the MMD menu, please replace it with another button. 的本地化字符串。
        /// </summary>
        internal static string HotkeyConflictMsg {
            get {
                return ResourceManager.GetString("HotkeyConflictMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut key conflict 的本地化字符串。
        /// </summary>
        internal static string HotkeyConflictTitle {
            get {
                return ResourceManager.GetString("HotkeyConflictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string ImageCompressOutPathButtonText {
            get {
                return ResourceManager.GetString("ImageCompressOutPathButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string ImageCompressPathText {
            get {
                return ResourceManager.GetString("ImageCompressPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageSize 的本地化字符串。
        /// </summary>
        internal static string ImageSizeText {
            get {
                return ResourceManager.GetString("ImageSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageType 的本地化字符串。
        /// </summary>
        internal static string ImageTypeText {
            get {
                return ResourceManager.GetString("ImageTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The shortcut key setting is invalid. Please re-enter. 的本地化字符串。
        /// </summary>
        internal static string invalidkey {
            get {
                return ResourceManager.GetString("invalidkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JPG/Webp/Avif Compression quality 的本地化字符串。
        /// </summary>
        internal static string JPGQualityText {
            get {
                return ResourceManager.GetString("JPGQualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys registered 的本地化字符串。
        /// </summary>
        internal static string Keyregistered {
            get {
                return ResourceManager.GetString("Keyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception occurred while terminating process: {0} 的本地化字符串。
        /// </summary>
        internal static string LogKillProcessException {
            get {
                return ResourceManager.GetString("LogKillProcessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get current frame number, frame number will be ignored and saved. 的本地化字符串。
        /// </summary>
        internal static string LogNoFrame {
            get {
                return ResourceManager.GetString("LogNoFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file was not saved successfully, maybe the input failed or the path is wrong. 的本地化字符串。
        /// </summary>
        internal static string LogSaveFail {
            get {
                return ResourceManager.GetString("LogSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file is saved in:{0} 的本地化字符串。
        /// </summary>
        internal static string LogSavePath {
            get {
                return ResourceManager.GetString("LogSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File saved successfully! 的本地化字符串。
        /// </summary>
        internal static string LogSaveSuccess {
            get {
                return ResourceManager.GetString("LogSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving:{0} 的本地化字符串。
        /// </summary>
        internal static string LogSaving {
            get {
                return ResourceManager.GetString("LogSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMD is not running. 的本地化字符串。
        /// </summary>
        internal static string MMDNotrunning {
            get {
                return ResourceManager.GetString("MMDNotrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter key 的本地化字符串。
        /// </summary>
        internal static string NewKey {
            get {
                return ResourceManager.GetString("NewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string OutPathButtonText {
            get {
                return ResourceManager.GetString("OutPathButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string OutPutText {
            get {
                return ResourceManager.GetString("OutPutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The export path is empty, please select the export path first! 的本地化字符串。
        /// </summary>
        internal static string PathEmpty {
            get {
                return ResourceManager.GetString("PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG level 的本地化字符串。
        /// </summary>
        internal static string PNGQualityText {
            get {
                return ResourceManager.GetString("PNGQualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMD FrameShot Save
        ///by:SaraKale
        ///
        ///This is a small tool for quickly saving images in MMD, saving the tedious process of manually saving images.
        ///
        ///Operating system requirements: Windows 7 SP1 and higher system versions
        ///
        ///Main features:
        ///1.  realistic simulation button saves images and can be configured with shortcut button binding.
        ///2. Customizable file names, image file types, and export paths, as well as additional image compression processing.
        ///3. Multiple images can be saved within a continuous frame r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PromptContentText {
            get {
                return ResourceManager.GetString("PromptContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please get the screen position at the &quot;+&quot; before saving! 的本地化字符串。
        /// </summary>
        internal static string PromptGetLocation {
            get {
                return ResourceManager.GetString("PromptGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the frame rate range before saving! 的本地化字符串。
        /// </summary>
        internal static string PromptInputFrameRange {
            get {
                return ResourceManager.GetString("PromptInputFrameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Fail 的本地化字符串。
        /// </summary>
        internal static string ReadFail {
            get {
                return ResourceManager.GetString("ReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey registration failed and may have been taken by another program. 的本地化字符串。
        /// </summary>
        internal static string Registrationfail {
            get {
                return ResourceManager.GetString("Registrationfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 resolution 的本地化字符串。
        /// </summary>
        internal static string ResolutionTipText {
            get {
                return ResourceManager.GetString("ResolutionTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically open the folder after saving 的本地化字符串。
        /// </summary>
        internal static string SaveAfterFolderText {
            get {
                return ResourceManager.GetString("SaveAfterFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        internal static string ShortcutKeysText {
            get {
                return ResourceManager.GetString("ShortcutKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Save 的本地化字符串。
        /// </summary>
        internal static string SingleFrameText {
            get {
                return ResourceManager.GetString("SingleFrameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Path 的本地化字符串。
        /// </summary>
        internal static string SourceDirectoryText {
            get {
                return ResourceManager.GetString("SourceDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string StopSaveButtonText {
            get {
                return ResourceManager.GetString("StopSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot switch to English input method automatically, please switch manually. 的本地化字符串。
        /// </summary>
        internal static string SwitchEnglishKeyboardFail {
            get {
                return ResourceManager.GetString("SwitchEnglishKeyboardFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string TabPage1Text {
            get {
                return ResourceManager.GetString("TabPage1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string TabPage2Text {
            get {
                return ResourceManager.GetString("TabPage2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        internal static string TabPage3Text {
            get {
                return ResourceManager.GetString("TabPage3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image settings 的本地化字符串。
        /// </summary>
        internal static string TabPage4Text {
            get {
                return ResourceManager.GetString("TabPage4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image adjustment 的本地化字符串。
        /// </summary>
        internal static string TabPage5Text {
            get {
                return ResourceManager.GetString("TabPage5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Topping 的本地化字符串。
        /// </summary>
        internal static string TopMostText {
            get {
                return ResourceManager.GetString("TopMostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Topping 的本地化字符串。
        /// </summary>
        internal static string TopMostTipText {
            get {
                return ResourceManager.GetString("TopMostTipText", resourceCulture);
            }
        }
    }
}
